### ISSUE TITLE
Local-storage-manager build test FAILs

### ISSUE THREAD

**Issue by vasap87** [StnetixDevTeam/ariADDna#78]
```
mvn clean install
```
on module Local-storage-manager
test fails:
```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.SimpleTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.065 sec <<< FAILURE! - in com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.SimpleTest
initializationError(com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.SimpleTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.Exception: Method simple() should be public
        at org.junit.runners.model.FrameworkMethod.validatePublicVoid(FrameworkMethod.java:96)
        at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java:74)
        at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
        at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
        at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
        at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

initializationError(com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.SimpleTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Exception: Method startService() should be public
        at org.junit.runners.model.FrameworkMethod.validatePublicVoid(FrameworkMethod.java:96)
        at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java:74)
        at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
        at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
        at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
        at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.FileSystemWatchingServiceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.FileSystemWatchingServiceTest
initializationError(com.stnetix.ariaddna.localstoragemanager.fileSystemWatchingService.FileSystemWatchingServiceTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: Method createFilesTest() should be public
        at org.junit.runners.model.FrameworkMethod.validatePublicVoid(FrameworkMethod.java:96)
        at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java:74)
        at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
        at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
        at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
        at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest
Tests run: 8, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 0.201 sec <<< FAILURE! - in com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest
getFileAttribute(com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.nio.file.NoSuchFileException: /tmp/AriaddnaTemp918832357628474516/temFFpFile0.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.FileAttributes.<init>(FileAttributes.java:36)
        at com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingService.getFileAttributes(LocalStoreIndexingService.java:90)
        at com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest.getFileAttribute(LocalStoreIndexingServiceTest.java:89)

findFilesByCreationDate(com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest)  Time elapsed: 0.109 sec  <<< FAILURE!
java.lang.AssertionError: expected:<5> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest.findFilesByCreationDate(LocalStoreIndexingServiceTest.java:73)

getLastModifyTime(com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at com.stnetix.ariaddna.localstoragemanager.localStoreIndexingService.LocalStoreIndexingServiceTest.getLastModifyTime(LocalStoreIndexingServiceTest.java:105)


Results :

Failed tests: 
  LocalStoreIndexingServiceTest.findFilesByCreationDate:73 expected:<5> but was:<0>
  LocalStoreIndexingServiceTest.getLastModifyTime:105 null

Tests in error: 
  SimpleTest.initializationError »  Method simple() should be public
  SimpleTest.initializationError »  Method startService() should be public
  FileSystemWatchingServiceTest.initializationError »  Method createFilesTest() ...
  LocalStoreIndexingServiceTest.getFileAttribute:89 » NoSuchFile /tmp/AriaddnaTe...

Tests run: 11, Failures: 2, Errors: 4, Skipped: 0

```

**Comment by kosmoflyko** [comment]
What is state for this task now?
On my local fork I see this  issue again

**Comment by vasap87** [comment]
This issue is actual.
